# Generated by Django 6.0.4 on 2026-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url_user_google_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='phone',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_type',
            field=models.CharField(choices=[('email_register', 'Email Registration'), ('email_reset', 'Email Password Reset')], max_length=30),
        ),
    ]
